pipeline {
    agent any

    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'echo "Building"'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'echo "Testing"'
                }
            }
        }

        stage('Package') {
            steps {
                script {
                    sh 'echo "Packaging"'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'echo "Deploying"'
                }
            }
        }

        stage('Clean Up') {
            steps {
                script {
                    sh 'echo "Cleaning Up"'
                }
            }
        }
    }
}
