pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'echo "Building"'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'echo "Testing"'
                }
            }
        }

        stage('Package') {
            steps {
                script {
                    sh 'echo "Packaging"'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'echo "Deploying"'
                }
            }
        }

        stage('Clean Up') {
            steps {
                script {
                    sh 'echo "Cleaning Up"'
                }
            }
        }
    }
}
