pipeline {
    agent any

    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }


  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

    stage('package') {
      steps {
        script {
          sh 'echo "packaging"'
        }
      }
    }
   

    stage('deploy') {
      steps {
        script {
          sh 'echo "deploying"'
        }
      }
    }

    stage('clean up') {
      steps {
        script {
          sh 'echo "cleaning up"'
        }
      }
    }
  }
}


